### PR TITLE
Log communication cost

### PR DESCRIPTION
**Pull request by rishi-s8**
A first attempt at logging the up and down communication costs in GRPC. A decorator on the sender's end and inside callback_fn at the receiver.

### CODE REVIEW

**Comment by tremblerz** [comment]
Why not GRPC's interceptor?

**Comment by rishi-s8** [comment]
It is doing the same thing, so this was just easier and more intuitive. grpc interceptor on the requestor's end is gonna have the same lines of code. On the sender's end, it still makes sense, but having a similar structure on both ends makes more sense.

**Comment by rishi-s8** [comment]
Also, given the structure of the algorithms, after each round, only the received communication cost will be reliable because of asynchrony.

**Comment by rishi-s8** [comment]
Tested with `fl_static.py` and `fl.py`

**Review by tremblerz — APPROVED** [review]

**Pull request merged**
