### PR TITLE
grpc benchmark initial

### PR DESCRIPTION
**Pull request by XThomasBU**
### Initial Setup for Benchmarking

- Follows the methods from https://github.com/facebookresearch/DomainBed/tree/main
- On a high level, follows the workflow detailed in `grpc_expts/benchmarking.md`

### TODO

- ~~Cleanup Code~~
-  ~~'Done' File not created for the runs~~
- ~~Bug Fixes and Enhancements (replace hard-coded values, create a table to aggregate and benchmark results, etc)~~
- ~~Fix how clients/server are assigned devices~~

### CODE REVIEW

**Comment by XThomasBU** [comment]
@tremblerz Added an initial pipeline for creating the sweep runs with the existing grpc code. Have shown an example at `grpc_expts/benchmarking.md`

**Comment by tremblerz** [comment]
@XThomasBU would you be interested in doing this again? We have fully migrated the codebase to grpc and it is much more stable now

**Comment by XThomasBU** [comment]
> @XThomasBU would you be interested in doing this again? We have fully migrated the codebase to grpc and it is much more stable now

Yes, Sorry. Will take a look at it now. Thank you!

**Comment by XThomasBU** [comment]
I apologise, I could not find much time to fully complete the implementation. I'll try to push a stable version over the next 2 weeks, if that still works. Thanks!

**Comment by tremblerz** [comment]
Let's do this in a new PR given that main branch has deviated quite a bit

**Pull request closed without merging**
